import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from "react";
import { Web3 } from "web3";
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [account, setAccount] = useState("");

  useEffect(() => {
    const ConnectMetaMask = async () => {
      try {
          window.ethereum.enable().then(async () => {
          const web3 = new Web3(window.ethereum);
          const accounts = await web3.eth.getAccounts();
          setAccount(accounts[0]);
          let config = {
            url: 'https://evm.ngd.network/api',
            method: "get",
            params: {
              module: "account",
              action: "eth_get_balance",
              address: "0x71Bc23122C04F3879D70f1F643aF7245Ae4bB578"
            }
          };
          let response = await axios.request(config);
          console.log(response);
        });
      } catch (error) {
        console.log(error);
      }
    };
    ConnectMetaMask();
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div className="p-4">
        {!account ? (
          <button onClick={() => window.ethereum.enable()}>
            Connect to MetaMask
          </button>
        ) : null}
        {account ? (
          <>
            <p>Your account address: {account} / NFT Balance: </p>
          </>
        ) : null}
        </div>
      </main>
    </>
  )
}
