import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect, useRef } from "react";
import { Web3 } from "web3";
import ABI from "@/contracts/NeoHackathonNFTABI.json"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const web = new Web3();
  const [account, setAccount] = useState("");

  useEffect(() => {
    console.log(window.ethereum.request);
    const ConnectMetaMask = async () => {
      try {
          window.ethereum.enable().then(async () => {
          // const accounts = await web3.eth.getAccounts();
          const accounts = await window.ethereum.request({ method: 'eth_accounts' });
          setAccount(accounts[0]);

        });
      } catch (error) {
        console.log(error);
      }
    };
    ConnectMetaMask();
  }, []);

  const balanceOf = async () => {
    try {
      const a = await web.eth.abi.encodeFunctionCall({
        name: 'safeMint',
        type: 'function',
        inputs: [{
            internalType: "address",
            type: 'address',
            name: 'to'
        }]
      }, [account]);
      console.log(a);
      try {
        const transactionHash = await window.ethereum.request({
          method: 'eth_sendTransaction',
          params: [
            {
              from: account, 
              to: "0x1968129459A41F38dfbB2771b19E4925A394A1E0",
              data: a,
            },
          ],
        });
        console.log(transactionHash);
      } catch (error) {
        console.error(error);
      }
    } catch (e) {
      console.log(e);
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div className="p-4">
        {!account ? (
          <button onClick={() => window.ethereum.enable()}>
            Connect to MetaMask
          </button>
        ) : null}
        {account ? (
          <>
          <button onClick={balanceOf}>bal</button>
            <p>Your account address: {account} / NFT Balance: </p>
          </>
        ) : null}
        </div>
      </main>
    </>
  )
}
